# Biodigester parameters

si_01       = None # boolean, discrete output coil, PLC reads
al_01       = None # boolean, discrete input coil, PLC writes
wi_02       = None # numerical, input register, PLC writes
si_02       = None # boolean, discrete output coil, PLC reads
al_02       = None # boolean, discrete input coil, PLC writes
hoa_02      = None # boolean, discrete output coil, PLC reads
si_03       = None # boolean, discrete output coil, PLC reads
al_03       = None # boolean, discrete input coil, PLC writes
ki_03       = None # numerical, input registers, PLC writes
li_03       = None # numerical, input registers, PLC writes
fsdl_03     = None # boolean, discrete output coil, PLC reads
fsdh_03     = None # boolean, discrete output coil, PLC reads
ki_04       = None # numerical, input registers, PLC writes
j_04        = None # numerical, input registers, PLC writes
hoa_01      = None # boolean
fit_04      = None # numerical, input registers, PLC writes
ti_06_1     = None # numerical, input registers, PLC writes
ti_06_2     = None # numerical, input registers, PLC writes
ty_06       = None # boolean, discrete input coil, PLC writes
lit_06      = None # numerical, input registers, PLC writes
lahh_06     = None # numerical, input registers, PLC writes
lah_06      = None # numerical, input registers, PLC writes
lal_06      = None # numerical, input registers, PLC writes
ti_06_4     = None # numerical, input registers, PLC writes
pi_06_3     = None # numerical, input registers, PLC writes
pi_11       = None # numerical, input registers, PLC writes
pi_14       = None # numerical, input registers, PLC writes
ti_14       = None # numerical, input registers, PLC writes
fit_13      = None # numerical, input registers, PLC writes
si_07       = None # boolean, discrete output coil, PLC reads
al_07       = None # boolean, discrete input coil, PLC writes
hoa_07      = None # boolean, discrete output coil, PLC reads
ki_07       = None # numerical, input registers, PLC writes
j_07        = None # numerical, input registers, PLC writes
lsdh_07     = None # boolean, discrete output coil, PLC reads
si_06       = None # boolean, discrete output coil, PLC reads
al_06       = None # boolean, discrete input coil, PLC writes
ti_15       = None # numerical, input registers, PLC writes
ti_16       = None # numerical, input registers, PLC writes

load_cells_max                      = 50
load_cells_min                      = 0
level_sensor_max                    = 50
level_sensor_min                    = 0
substrate_flowrate_max              = 50
substrate_flowrate_min              = 0
substrate_temperature_max           = 50
substrate_temperature_min           = 0
substrate_level_highest_max         = 50
substrate_level_max                 = 45
substrate_level_min                 = 0
biogas_temperature_max              = 50
biogas_temperature_min              = 0
biogas_pressure_max                 = 50
biogas_pressure_min                 = 0
biogas_output_flowrate_max          = 50
biogas_output_flowrate_min          = 0
substrate_recycling_temperature_max = 50
substrate_recycling_temperature_min = 0
timers_value_max                    = 50
timers_value_min                    = 0
inverters_frequency_max             = 50
inverters_frequency_min             = 0

# Chiller parameters
vg1         = None # numerical, input registers, PLC writes
vh1         = None # numerical, input registers, PLC writes
vc1         = None # numerical, input registers, PLC writes
vc2         = None # numerical, input registers, PLC writes
pc1         = None # numerical, input registers, PLC writes
pg1         = None # numerical, input registers, PLC writes
tg1         = None # numerical, input registers, PLC writes
th1         = None # numerical, input registers, PLC writes
th2         = None # numerical, input registers, PLC writes
th3         = None # numerical, input registers, PLC writes
th4         = None # numerical, input registers, PLC writes
tc1         = None # numerical, input registers, PLC writes
tc2         = None # numerical, input registers, PLC writes
tc3         = None # numerical, input registers, PLC writes
tc4         = None # numerical, input registers, PLC writes
tc5         = None # numerical, input registers, PLC writes
tc6         = None # numerical, input registers, PLC writes
tc7         = None # numerical, input registers, PLC writes
tc8         = None # numerical, input registers, PLC writes
tc9         = None # numerical, input registers, PLC writes
ch1         = None # boolean, discrete output coil, PLC reads
cc1         = None # boolean, discrete output coil, PLC reads
cc2         = None # boolean, discrete output coil, PLC reads

chiller_temp_max        = 0
chiller_temp_min        = 40
chiller_pressure_max    = 6
chiller_pressure_min    = 5
chiller_flowrate_max    = 300
chiller_flowrate_min    = 200