# Biodigester parameters

si_01       = None # boolean, discrete output coil, PLC reads
al_01       = None # boolean, discrete input coil, PLC writes
lc_1        = None # numerical, input register, PLC writes
lc_2        = None # numerical, input register, PLC writes
lc_3        = None # numerical, input register, PLC writes
lc_4        = None # numerical, input register, PLC writes
ki_02       = None # numerical, input register, PLC writes
si02        = None # boolean, discrete output coil, PLC reads
al02        = None # boolean, discrete input coil, PLC writes
hoa_02      = None # boolean
si_03       = None # boolean, discrete output coil, PLC reads
ki_03       = None # numerical
al_03       = None # boolean, discrete input coil, PLC writes
i_i_03      = None # numerical
i_c_03      = None # numerical
si_04       = None # boolean, discrete output coil, PLC reads
ki_04       = None # numerical
al_04       = None # boolean, discrete input coil, PLC writes
hoa_04      = None # boolean
si_05       = None # boolean, discrete output coil, PLC reads
ki_05       = None # numerical
al_05       = None # boolean, discrete input coil, PLC writes
i_i_05      = None # numerical
i_c_05      = None # numerical
fy_05       = None # boolean
lsdh_05     = None # boolean
fsdh_05     = None # numerical
fsl_05      = None # numerical
hli_05      = None # numerical
lli_05      = None # numerical
ti_16       = None # numerical
pit_16_1    = None # numerical
pit_16_2    = None # numerical
ti_06_1     = None # numerical
ti_06_2     = None # numerical
ti_06_3     = None # numerical
ti_06_4     = None # numerical
ti_06_5     = None # numerical
ti_06_6     = None # numerical
pit_06_1    = None # numerical
pit_06_2    = None # numerical
pit_06_3    = None # numerical
si_06       = None # boolean, discrete output coil, PLC reads
si_07       = None # boolean, discrete output coil, PLC reads
ki_06       = None # numerical
ki_07       = None # numerical
al_06       = None # boolean, discrete input coil, PLC writes
al_07       = None # boolean, discrete input coil, PLC writes
hoa_06      = None # boolean
hoa_07      = None # boolean
hs_06       = None # boolean
hs_07       = None # boolean
lal_06      = None # numerical
lah_06      = None # numerical
lahh_06     = None # numerical
hs_08       = None # boolean
si_08       = None # boolean, discrete output coil, PLC reads
ki_08       = None # numerical
al_08       = None # boolean, discrete input coil, PLC writes
ls_08       = None # numerical
hoa_08      = None # boolean
fit_14      = None # numerical
pit_14      = None # numerical
ti_14       = None # numerical
bi_15       = None # boolean
pdl_11      = None # numerical
pdl_12      = None # numerical
pdal_11     = None # numerical
bs_15       = None # boolean
bal_15      = None # boolean

# Chiller parameters
vg1         = None # numerical, input registers, PLC writes
vh1         = None # numerical, input registers, PLC writes
vc1         = None # numerical, input registers, PLC writes
vc2         = None # numerical, input registers, PLC writes
pc1         = None # numerical, input registers, PLC writes
pg1         = None # numerical, input registers, PLC writes
tg1         = None # numerical, input registers, PLC writes
th1         = None # numerical, input registers, PLC writes
th2         = None # numerical, input registers, PLC writes
th3         = None # numerical, input registers, PLC writes
th4         = None # numerical, input registers, PLC writes
tc1         = None # numerical, input registers, PLC writes
tc2         = None # numerical, input registers, PLC writes
tc3         = None # numerical, input registers, PLC writes
tc4         = None # numerical, input registers, PLC writes
tc5         = None # numerical, input registers, PLC writes
tc6         = None # numerical, input registers, PLC writes
tc7         = None # numerical, input registers, PLC writes
tc8         = None # numerical, input registers, PLC writes
tc9         = None # numerical, input registers, PLC writes
ch1         = None # boolean, discrete output coil, PLC reads
cc1         = None # boolean, discrete output coil, PLC reads
cc2         = None # boolean, discrete output coil, PLC reads

chiller_temp_max = 0
chiller_temp_min = 40
chiller_pressure_max = 6
chiller_pressure_min = 5
chiller_flowrate_max = 300
chiller_flowrate_min = 200